name: web_crawler
version: 0.0.4
author: Brandon White <jennexproject+webcrawler@gmail.com>
description: A framework for crawling websites for urls.
homepage: http://jennex.it/
dependencies:
  html: '>=0.12.1 <1.0.0'
  server_logger:
    git: https://github.com/bwhite000/server-logger.git
